# Generated by Django 4.2.1 on 2023-07-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='nick',
        ),
    ]
