# Generated by Django 4.2.1 on 2023-07-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='profile',
            new_name='user',
        ),
    ]
