# Generated by Django 4.2.1 on 2023-07-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_room_user_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='entry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
