# Generated by Django 4.2.1 on 2023-07-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_room_entry_count_alter_room_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='entry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
